// Supabase RPC／trigger 例外代碼 → 使用者可讀訊息與 HTTP 狀態。
import { json } from "./http";

export const databaseErrors: Record<string, string> = {
  LOGIN_REQUIRED: "需要會員登入",
  PROFILE_INCOMPLETE: "請先完成姓名與手機資料",
  INVALID_PICKUP_PLAN: "取貨方式不正確",
  INVALID_DELIVERY_METHOD: "取貨方式不正確",
  INVALID_SHIPPING_UNITS: "商品裝箱設定不正確",
  SHIPPING_SETTINGS_NOT_FOUND: "配送設定尚未完成",
  INVALID_SHIPPING_SETTINGS: "配送設定不正確",
  SHIPPING_ADDRESS_REQUIRED: "宅配請填寫收件地址",
  SHIPPING_RECIPIENT_REQUIRED: "宅配請填寫收件人姓名",
  SHIPPING_PHONE_REQUIRED: "宅配請填寫有效的收件人手機號碼",
  INVALID_DISCOUNT: "折扣資料不正確",
  EMPTY_CART: "購物車不可為空",
  BANK_ACCOUNT_REQUIRED: "請選擇收款帳戶",
  INVALID_PAYMENT_METHOD: "付款方式不正確",
  // store_payment 內部標記只給賣貨便（7-11 外部收款）；到店取貨與宅配一律匯款／轉帳
  STORE_PAYMENT_BANK_TRANSFER_ONLY: "本站到店取貨與宅配訂單僅接受匯款／轉帳，請改選匯款付款",
  STORE_PAYMENT_PREORDER_NOT_ALLOWED: "預購商品必須先匯款支付訂金",
  SELLER_BANK_PREORDER_ONLY: "賣貨便匯款訂單僅適用預購商品",
  MIXED_ORDER_NOT_ALLOWED: "現貨與預購需分開建立訂單，請回購物車分組結帳",
  CART_TOO_LARGE: "購物車品項數量超過上限",
  CART_ITEM_INVALID: "購物車商品資料不正確",
  CART_DUPLICATE_ITEM: "購物車中不可重複相同商品規格",
  CART_PRODUCT_NOT_FOUND: "購物車內有商品已下架，請重新整理",
  INVALID_BANK_ACCOUNT: "收款帳戶無效或已停用",
  INVALID_PAYMENT_LAST_FIVE: "匯款帳號末五碼格式不正確",
  INVALID_FINAL_PAYMENT_LAST_FIVE: "尾款匯款末五碼格式不正確",
  INVALID_SHIPPING_FEE: "實際運費必須是 0 或正整數",
  SHIPPING_FEE_STORE_PICKUP: "到店取貨不可設定寄送運費",
  SELLER_DELIVERY_NO_SHIPPING_FEE: "賣貨便運費由 7-11 向客戶收取，不計入訂單",
  SELLER_DELIVERY_EXTERNAL_ONLY: "賣貨便請前往 7-ELEVEN 賣貨便完成結帳，本站不建立賣貨便訂單",
  FINAL_PAYMENT_REQUIRED: "請填寫尾款匯款末五碼並確認尾款與運費已入帳",
  FINAL_PAYMENT_NOT_ALLOWED: "訂單尚未進入可出貨或可取貨狀態",
  ORDER_FULFILLMENT_NOT_EDITABLE: "此訂單目前不可修改尾款或運費資訊",
  INVALID_QUANTITY: "商品數量不正確",
  PRODUCT_NOT_FOUND: "商品已下架或不存在",
  INSUFFICIENT_STOCK: "商品庫存不足，請重新整理購物車",
  ORDER_NOT_PAYABLE: "訂單已逾期、已回報付款或無法付款",
  LINE_FRIEND_REQUIRED: "請先加入官方 LINE，並重新檢查好友狀態",
  ORDER_RATE_LIMITED: "近期建立訂單次數過多，請稍後再試",
  PENDING_ORDER_LIMIT: "目前待處理訂單已達上限，請等待客服確認",
  PURCHASE_LIMIT_EXCEEDED: "已達此商品的會員限購數量",
  DUPLICATE_ORDER_ITEM: "購物車中不可重複相同商品規格",
  REQUEST_BODY_TOO_LARGE: "請求內容過大，請縮減購物車或欄位內容",
  ADMIN_REQUIRED: "僅限管理員使用",
  REQUIRED_FIELDS_MISSING: "請填寫所有必填欄位",
  INVALID_NUMBER: "價格或庫存數量不正確",
  INVALID_PURCHASE_LIMIT: "限購數量必須為正整數或不限購",
  INVALID_DEPOSIT_RATE: "訂金比例不正確",
  PREORDER_DEPOSIT_MUST_BE_HALF: "預購商品訂金比例必須為 50%",
  ZERO_ADJUSTMENT: "庫存異動數量不可為 0",
  REASON_REQUIRED: "請填寫庫存異動原因",
  VARIANT_NOT_FOUND: "找不到商品規格",
  NEGATIVE_STOCK: "庫存不可小於 0",
  BELOW_RESERVED_STOCK: "調整後庫存不可低於已保留數量",
  ORDER_NOT_FOUND: "找不到訂單",
  ORDER_STATUS_UNCHANGED: "訂單狀態沒有變更",
  INVALID_ORDER_TRANSITION: "此訂單目前不可切換到指定狀態",
  SELLER_DELIVERY_SHIPPED_REQUIRES_REFUND: "賣貨便已進入出貨狀態，請走退款與退貨驗收流程",
  ORDER_NOTE_REQUIRED: "取消或退款相關操作必須填寫原因",
  REFUND_AMOUNT_REQUIRED: "請填寫退款金額（沒有退款請填 0）",
  INVALID_REFUND_AMOUNT: "退款金額不正確：必須是 0 或正整數，且不可超過訂單應付總額加運費",
  REFUND_NOT_ALLOWED_UNPAID: "未付款的訂單沒有可退的金額",
  REFUND_AMOUNT_NOT_APPLICABLE: "只有取消訂單或確認已退款時可以填寫退款金額",
  PARTIAL_READY_REQUIRES_SPLIT: "只有分批取貨訂單可標記為部分可取貨",
  PAYMENT_REPORT_REQUIRED: "會員尚未回報匯款末五碼",
  MEMBER_NOT_FOUND: "找不到會員",
  ZERO_POINT_ADJUSTMENT: "點數異動不可為 0",
  INSUFFICIENT_POINTS: "會員點數不足，無法扣除",
  INVALID_POINT_SETTINGS: "點數規則設定不正確",
  DISCOUNTS_NOT_ENABLED: "點數與優惠券折抵功能尚未啟用",
  DISCOUNTS_NOT_VERIFIED: "折扣必須由系統驗證",
  INVALID_COUPON: "優惠券設定不正確",
  COUPON_CODE_EXISTS: "優惠碼已存在",
  COUPON_NOT_FOUND: "找不到優惠券",
  COUPON_EXPIRED: "優惠券已失效或尚未開始",
  COUPON_NOT_ELIGIBLE: "此優惠券不適用於這個會員",
  COUPON_PRODUCT_NOT_ELIGIBLE: "購物車中沒有符合優惠券的商品",
  COUPON_USAGE_LIMIT: "優惠券總使用次數已達上限",
  COUPON_MEMBER_LIMIT: "您已達此優惠券的使用上限",
  COUPON_POINTS_NOT_COMBINABLE: "此優惠券不可與點數併用",
  INVALID_POINTS: "點數使用數量不正確",
  POINT_MINIMUM: "未達最低點數折抵門檻",
  POINT_LIMIT_EXCEEDED: "點數折抵超過本筆訂單上限",
  INVALID_RETURN_QUANTITY: "退貨收到、可再售與報廢數量不正確",
  RETURN_EXCEEDS_SOLD_QUANTITY: "退貨收到數量不可超過原購買數量",
  RETURN_EXCEEDS_SALE_MOVEMENT: "退貨數量不可超過原扣庫存數量",
  RETURN_REQUIRES_REFUNDED_ORDER: "訂單完成退款後才能確認實際退貨",
  RETURN_ALREADY_CONFIRMED: "此商品退貨已確認，不可重複回補",
  SALE_ALREADY_RESTOCKED: "此筆銷售庫存已回補，不可重複入庫",
  SALE_MOVEMENT_NOT_FOUND: "找不到原始銷售庫存異動",
  ORDER_ITEM_NOT_FOUND: "找不到訂單商品",
  INVALID_BIRTHDAY_SETTINGS: "生日券設定不正確",
  BANK_ACCOUNT_NOT_FOUND: "找不到收款帳戶",
  CATEGORY_NOT_FOUND: "找不到商品分類",
  CATEGORY_NAME_EXISTS: "分類名稱已存在",
  INVALID_CATEGORY: "商品分類資料不正確",
  INVALID_VARIANT: "商品規格資料不正確",
  SKU_EXISTS: "SKU 已存在",
  VARIANT_NAME_EXISTS: "此商品已有同名的規格，請換一個規格名稱",
  INVALID_PRODUCT: "商品資料不正確",
  INVALID_COMPARE_AT_PRICE: "原價資料不正確",
  AUDIT_LOG_IMMUTABLE: "稽核紀錄不可修改或刪除",
  AUDIT_TARGET_REQUIRED: "稽核目標不可為空",
  INVALID_IMAGE_PATH: "商品圖片資料不正確",
  PRODUCT_IMAGE_LIMIT: "每件商品最多 10 張照片",
  PRODUCT_IMAGE_NOT_FOUND: "找不到這張商品照片",
  INVALID_IMAGE_ORDER: "照片排序與目前照片不一致，請重新整理後再試",
  INVALID_PRODUCT_SHOWCASE: "展示設定格式錯誤：介紹上限 8000 字、導購文上限 80 字、輪播排序 1–12",
  INVALID_ADMIN_ORDER_FILTER: "訂單篩選條件不正確",
  INVALID_NOTIFICATION_STATUS: "通知狀態篩選條件不正確",
  NOTIFICATION_NOT_FOUND: "找不到通知紀錄",
  NOTIFICATION_REQUEUE_NOT_ALLOWED: "只有失敗通知可以重新排入"
};

export async function databaseError(response: Response) {
  let payload: { message?: string } = {};
  try { payload = await response.json() as { message?: string }; } catch { /* ignore malformed upstream errors */ }
  const matched = Object.keys(databaseErrors).find((code) => payload.message?.includes(code));
  const status = matched === "LINE_FRIEND_REQUIRED" ? 403 : response.status >= 500 ? 503 : 400;
  return json({ error: matched ? databaseErrors[matched] : "訂單服務暫時無法處理" }, { status });
}
