#!/usr/bin/env bash
# 交易測試：在一般 PostgreSQL（需 pg_cron）上建立全新資料庫，依序套用 Supabase 模擬層與全部 migration（並寫入 migration 紀錄），
# 核對紀錄與 supabase/migrations/ 一致、執行 verify_schema.sql，再跑 tests/db/*.test.sql。每個測試案例自行 begin … rollback。
#
# 連線使用標準 PG* 環境變數（PGHOST、PGPORT、PGUSER、PGPASSWORD）；資料庫名稱由 CJ_TEST_DB 指定，
# 預設 cj_test，且必須與 postgresql.conf 的 cron.database_name 相同。會刪除並重建該資料庫，
# 絕對不要指向正式或共用資料庫。
set -euo pipefail

cd "$(dirname "$0")/../.."
DB="${CJ_TEST_DB:-cj_test}"
export PGOPTIONS="${PGOPTIONS:-} -c client_min_messages=warning"
PSQL=(psql -X -q -v ON_ERROR_STOP=1 --no-psqlrc)

case "$DB" in
  postgres|template0|template1) echo "refusing to use database '$DB'" >&2; exit 1 ;;
esac

"${PSQL[@]}" -d postgres -c "drop database if exists \"$DB\" with (force)" -c "create database \"$DB\""
"${PSQL[@]}" -d "$DB" -f tests/db/supabase-shim.sql

count=0
for migration in supabase/migrations/*.sql; do
  if ! output=$("${PSQL[@]}" -d "$DB" -f "$migration" 2>&1); then
    echo "migration failed: $migration" >&2
    echo "$output" >&2
    exit 1
  fi
  # 與 Supabase CLI 相同，以檔名的版本與名稱記錄已套用的 migration。
  base=$(basename "$migration" .sql)
  "${PSQL[@]}" -d "$DB" -c "insert into supabase_migrations.schema_migrations(version, name) values ('${base%%_*}', '${base#*_}')"
  count=$((count + 1))
done
echo "applied $count migrations"

# 紀錄必須與 supabase/migrations/ 完全一致（同一段 SQL 可貼到正式專案檢查）。
history_issues=$(node tests/migration-history-sql.mjs | "${PSQL[@]}" -At -d "$DB")
if [ -n "$history_issues" ]; then
  echo "migration history does not match supabase/migrations:" >&2
  echo "$history_issues" >&2
  exit 1
fi
echo "migration history matches supabase/migrations"

failed_checks=$({ echo "with v as ("; sed '1d;$ s/;$//' supabase/verify_schema.sql; echo ") select e.key from v, jsonb_each(to_jsonb(v)) e where e.value::text <> 'true';"; } | "${PSQL[@]}" -At -d "$DB")
if [ -n "$failed_checks" ]; then
  echo "verify_schema.sql checks not true:" >&2
  echo "$failed_checks" >&2
  exit 1
fi
echo "verify_schema.sql: all checks true"

# 選擇性：把套用全部 migration 後、跑測試前的目前生效函式定義寫到 CJ_FUNCTION_SNAPSHOT
# 指定的檔案，方便追查某支 RPC「目前真正生效」的版本；未設定則整段略過。
if [ -n "${CJ_FUNCTION_SNAPSHOT:-}" ]; then
  {
    echo "-- effective function definitions in schemas public and private"
    echo "-- generated by tests/db/run.sh after applying $count migrations; do not edit by hand"
    "${PSQL[@]}" -At -d "$DB" -c "
      select pg_get_functiondef(p.oid) || E';\n'
        from pg_proc p
        join pg_namespace n on n.oid = p.pronamespace
       where n.nspname in ('public', 'private')
         and p.prokind in ('f', 'p')
         and not exists (select 1 from pg_depend d where d.classid = 'pg_proc'::regclass and d.objid = p.oid and d.deptype = 'e')
       order by n.nspname, p.proname, pg_get_function_identity_arguments(p.oid);
    "
  } > "$CJ_FUNCTION_SNAPSHOT"
  echo "wrote effective function snapshot to $CJ_FUNCTION_SNAPSHOT"
fi

"${PSQL[@]}" -d "$DB" -f tests/db/helpers.sql

status=0
for test_file in tests/db/*.test.sql; do
  if output=$("${PSQL[@]}" -d "$DB" -f "$test_file" 2>&1 >/dev/null); then
    echo "ok   $test_file"
  else
    echo "FAIL $test_file" >&2
    echo "$output" | grep -E "ERROR|ASSERTION|LINE [0-9]+|psql:" >&2 || echo "$output" >&2
    status=1
  fi
done
exit $status
